# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
description: 'Run the arduino-builder for all sketches and see if they compile'
author: 'Leon Kiefer'
inputs: 
  sketch:
    description: 'Path to a single sketch'
    required: false
  sketchDirectory:
    description: 'Directory in which to search for sketches'
    default: 'examples'
  board:
    description: 'Fully Qualified Board Name'
    default: 'arduino:avr:uno'
  libraries:
    description: |
      Directory containing Arduino libraries.
      Use this directory to install required 3rd-party libraries.
    default: 'libraries'
  hardware:
    description: 'Directory containing Arduino platforms'
    default: 'hardware'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'server'  
  color: 'blue'
